export const init_order_detail = 'init_order_detail'
export const init_order_list_params = 'init_order_list_params'
export const set_load_page_number = 'set_load_page_number'
export const set_refresh_page_number = 'set_refresh_page_number'
export const init_already_order = 'init_already_order'
